"""add_project_is_active_drop_legacy_columns

B-1 rename: was misnamed "create_project_table"; this migration actually adds the
is_active boolean to the project table and drops legacy columns (value, end_date,
start_date, status). Renamed to reflect actual content.

Revision ID: 32d7cd9ae5ab
Revises: 5618a8603e02
Create Date: 2026-02-15 16:32:19.282451

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '32d7cd9ae5ab'
down_revision: Union[str, Sequence[str], None] = '5618a8603e02'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.drop_column('project', 'value')
    op.drop_column('project', 'end_date')
    op.drop_column('project', 'start_date')
    op.drop_column('project', 'status')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('status', postgresql.ENUM('ACTIVE', 'ON_HOLD', 'COMPLETED', 'CANCELLED', name='projectstatus'), autoincrement=False, nullable=False, server_default='ACTIVE'))
    op.add_column('project', sa.Column('start_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('project', sa.Column('end_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('project', sa.Column('value', sa.NUMERIC(precision=14, scale=2), autoincrement=False, nullable=True))
    op.drop_column('project', 'is_active')
    # ### end Alembic commands ###
