"""add_controls_foundation

Revision ID: 4a20343b5408
Revises: ec08c27d8523
Create Date: 2026-02-12 20:54:36.214056

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '4a20343b5408'
down_revision: Union[str, Sequence[str], None] = 'ec08c27d8523'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Manually create Enums using raw SQL to ensure they exist
    op.execute("DO $$ BEGIN CREATE TYPE portfoliorole AS ENUM ('PortfolioAdmin', 'CommercialManager', 'CostEngineer', 'Viewer'); EXCEPTION WHEN duplicate_object THEN null; END $$;")
    op.execute("DO $$ BEGIN CREATE TYPE workflowstatus AS ENUM ('Draft', 'Submitted', 'Approved', 'Locked', 'Cancelled'); EXCEPTION WHEN duplicate_object THEN null; END $$;")

    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('portfolio_id', sa.Integer(), nullable=True),
    sa.Column('actor_user_id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('entity_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('action', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('before_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('after_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_log_actor_user_id'), 'audit_log', ['actor_user_id'], unique=False)
    op.create_index(op.f('ix_audit_log_company_id'), 'audit_log', ['company_id'], unique=False)
    op.create_index(op.f('ix_audit_log_entity_id'), 'audit_log', ['entity_id'], unique=False)
    op.create_index(op.f('ix_audit_log_entity_type'), 'audit_log', ['entity_type'], unique=False)
    op.create_index(op.f('ix_audit_log_portfolio_id'), 'audit_log', ['portfolio_id'], unique=False)
    op.create_table('financial_note',
    sa.Column('status', postgresql.ENUM('Draft', 'Submitted', 'Approved', 'Locked', 'Cancelled', name='workflowstatus', create_type=False), nullable=False),
    sa.Column('locked_at', sa.DateTime(), nullable=True),
    sa.Column('locked_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_user_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('amount', sa.Numeric(), nullable=False),
    sa.Column('portfolio_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['locked_by_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolio.id'], ),
    sa.ForeignKeyConstraint(['updated_by_user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_financial_note_status'), 'financial_note', ['status'], unique=False)
    op.alter_column('portfolio_user', 'role',
               existing_type=sa.VARCHAR(),
               type_=postgresql.ENUM('PortfolioAdmin', 'CommercialManager', 'CostEngineer', 'Viewer', name='portfoliorole', create_type=False),
               existing_nullable=False,
               postgresql_using='role::portfoliorole')
    op.drop_index(op.f('ix_portfolio_user_portfolio_id'), table_name='portfolio_user')
    op.drop_index(op.f('ix_portfolio_user_user_id'), table_name='portfolio_user')
    op.create_index(op.f('ix_portfolio_user_role'), 'portfolio_user', ['role'], unique=False)
    op.drop_constraint(op.f('portfolio_user_company_id_fkey'), 'portfolio_user', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(op.f('portfolio_user_company_id_fkey'), 'portfolio_user', 'company', ['company_id'], ['id'])
    op.drop_index(op.f('ix_portfolio_user_role'), table_name='portfolio_user')
    op.create_index(op.f('ix_portfolio_user_user_id'), 'portfolio_user', ['user_id'], unique=False)
    op.create_index(op.f('ix_portfolio_user_portfolio_id'), 'portfolio_user', ['portfolio_id'], unique=False)
    op.alter_column('portfolio_user', 'role',
               existing_type=sa.Enum('PORTFOLIO_ADMIN', 'COMMERCIAL_MANAGER', 'COST_ENGINEER', 'VIEWER', name='portfoliorole'),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.drop_index(op.f('ix_financial_note_status'), table_name='financial_note')
    op.drop_table('financial_note')
    op.drop_index(op.f('ix_audit_log_portfolio_id'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_entity_type'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_entity_id'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_company_id'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_actor_user_id'), table_name='audit_log')
    op.drop_table('audit_log')
    
    # Manually drop Enums
    op.execute("DROP TYPE IF EXISTS workflowstatus")
    op.execute("DROP TYPE IF EXISTS portfoliorole")
    # ### end Alembic commands ###
