"""cleanup_indexes_and_constraints

B-1 rename: was misnamed "create project table"; this migration actually removes the
financial_note status index, makes portfolio_user.role nullable, and drops the
portfolio_user role index. Renamed to reflect actual content.

Revision ID: 5618a8603e02
Revises: c41d24b0c3dc
Create Date: 2026-02-15 13:51:05.218971

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5618a8603e02'
down_revision: Union[str, Sequence[str], None] = 'c41d24b0c3dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_financial_note_status'), table_name='financial_note')
    op.alter_column('portfolio_user', 'role',
               existing_type=postgresql.ENUM('PortfolioAdmin', 'CommercialManager', 'CostEngineer', 'Viewer', name='portfoliorole'),
               nullable=True)
    op.drop_index(op.f('ix_portfolio_user_role'), table_name='portfolio_user')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_portfolio_user_role'), 'portfolio_user', ['role'], unique=False)
    op.alter_column('portfolio_user', 'role',
               existing_type=postgresql.ENUM('PortfolioAdmin', 'CommercialManager', 'CostEngineer', 'Viewer', name='portfoliorole'),
               nullable=False)
    op.create_index(op.f('ix_financial_note_status'), 'financial_note', ['status'], unique=False)
    # ### end Alembic commands ###
