"""Add_multi_tenancy

Revision ID: ec08c27d8523
Revises: 35426f623d75
Create Date: 2026-02-12 19:39:40.991282

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'ec08c27d8523'
down_revision: Union[str, Sequence[str], None] = '35426f623d75'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_company_slug'), 'company', ['slug'], unique=True)
    op.create_table('portfolio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'code', name='_company_portfolio_code_uc')
    )
    op.create_index(op.f('ix_portfolio_code'), 'portfolio', ['code'], unique=False)
    op.create_index(op.f('ix_portfolio_company_id'), 'portfolio', ['company_id'], unique=False)
    op.create_table('portfolio_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('portfolio_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolio.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'portfolio_id', name='_user_portfolio_uc')
    )
    op.create_index(op.f('ix_portfolio_user_company_id'), 'portfolio_user', ['company_id'], unique=False)
    op.create_index(op.f('ix_portfolio_user_portfolio_id'), 'portfolio_user', ['portfolio_id'], unique=False)
    op.create_index(op.f('ix_portfolio_user_user_id'), 'portfolio_user', ['user_id'], unique=False)
    op.add_column('user', sa.Column('company_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_user_company_id'), 'user', ['company_id'], unique=False)
    op.create_foreign_key(None, 'user', 'company', ['company_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_index(op.f('ix_user_company_id'), table_name='user')
    op.drop_column('user', 'company_id')
    op.drop_index(op.f('ix_portfolio_user_user_id'), table_name='portfolio_user')
    op.drop_index(op.f('ix_portfolio_user_portfolio_id'), table_name='portfolio_user')
    op.drop_index(op.f('ix_portfolio_user_company_id'), table_name='portfolio_user')
    op.drop_table('portfolio_user')
    op.drop_index(op.f('ix_portfolio_company_id'), table_name='portfolio')
    op.drop_index(op.f('ix_portfolio_code'), table_name='portfolio')
    op.drop_table('portfolio')
    op.drop_index(op.f('ix_company_slug'), table_name='company')
    op.drop_table('company')
    # ### end Alembic commands ###
